packages: []
catalogs:
  backend:
    '@types/pg': ^8.15.6
    better-auth: ^1.3.34
    drizzle-kit: ^0.31.6
    drizzle-orm: ^0.44.7
    pg: ^8.16.3
  build:
    '@nuxt/devtools': ^3.0.0-beta.2
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.2.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.4
    '@unocss/nuxt': ^66.5.4
    '@vueuse/nuxt': ^14.0.0
    dotenv: ^17.2.3
    nuxt: ^4.2.0
    unocss: ^66.5.4
    unplugin: ^2.3.10
    vite: ^7.1.12
  dev:
    '@antfu/eslint-config': ^6.1.0
    eslint: ^9.38.0
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.2
  frontend:
    '@nuxtjs/i18n': ^10.1.2
    '@vueuse/core': ^14.0.0
    pinia: ^3.0.3
    vue: ^3.5.22
  icons:
    '@iconify-json/lucide': ^1.2.71

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
